name: Testing Snyk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job Name
  snyk-pipeline:
    
    runs-on: ubuntu-latest
    
    steps:      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install build dependencies
      run: python -m pip install -U setuptools wheel build
    - name: Build
      run: python -m build .
    - name: Publish
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
        skip_existing: true
    - name: Create append_cmd
      env:
          append_cmd: "--file=setup.py --skip-unresolved=false"
      run: echo ${append_cmd}
        
      # Running Snyk
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/setup@master
      continue-on-error: true
    - name: Snyk Monitor
      run: snyk monitor -d --org=774fd541-8351-4b80-9b89-8998e4a5ac89 --file=setup.py
      env:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
